# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.CharField(blank=True, choices=[('i+', 'i+'), ('i-', 'i-'), ('i0', 'i0'), ('s+', 's+'), ('s-', 's-'), ('s0', 's0'), ('o', 'o')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('key', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('overview', models.TextField()),
                ('cl_phase_1', models.CharField(max_length=256)),
                ('cl_phase_2', models.CharField(max_length=256)),
                ('cl_phase_3', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Drug'),
        ),
    ]
