# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='cui',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='mdr1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
