# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='annotator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='annotator.Person'),
            preserve_default=False,
        ),
    ]
