# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0004_drug_annotator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together=set([('key', 'cui', 'mdr1')]),
        ),
    ]
